before_script:
  - psql -c "CREATE DATABASE bestb4_test;" -U postgres

before_install:
 - gem update --system
 - gem install bundler

rvm:
  '2.6.3'

script:
 - bundle exec rspec spec

services:
  - postgresql
